spring.datasource.url=jdbc:mysql://localhost:3306/logimarket
spring.datasource.username=root
spring.datasource.password=tu_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mirror.datasource.url=jdbc:mysql://localhost:3306/logimarket_mirror
mirror.datasource.username=root
mirror.datasource.password=tu_password

server.port=8080
