# Servidor de BD Operacional (origen)
bd.url=jdbc:mysql://localhost:3306/loginmarket
bd.usuario=root
bd.password=lolaso123

# Servidor de DataWarehouse (destino)
dw.url=jdbc:mysql://localhost:3306/logimarket_dw
dw.usuario=root
dw.password=lolaso123
